# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: mySkilletbuildertut
# label used for menu selection
label: mySkilletbuildertutlabel
description: this is for tag edls

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - sbtut

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: edl_name
    description: edl name
    default: my_edl
    type_hint: text
  - name: edl_description
    description: what edl
    default: edl desc
    type_hint: text
  - name: edl_url
    description: edl url
    default: the edl url
    type_hint: text
  - name: tag_name
    description: tag name
    default: tag name
    type_hint: text 
  - name: tag_description
    description: tag description
    default: tag desc
    type_hint: text
  - name: tag_color
    description: sample dropdown list
    default: color1
    type_hint: dropdown
    dd_list:
      - key: red
        value: color1
      - key: blue
        value: color3
      - key: orange
        value: color6
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: edl
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/external-list
    file: edl.xml
  - name: tag
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/tag
    file: tag.xml
  - name: rules
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security
    file: rules.xml
# ---------------------------------------------------------------------
# end of snippets section